import type { ClosetItem } from "../types";
import { uid, todayISO } from "./money";

export const demoItems: ClosetItem[] = [
  {
    id: uid(),
    imageUrl:
      "https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=600&q=80",
    name: "Vestido midi floral",
    category: "Vestidos",
    brand: "Farm",
    store: "Farm Online",
    originalPrice: 449.9,
    currentPrice: 359.9,
    buyLink: "https://www.farmrio.com.br",
    color: "Rosa",
    size: "M",
    priority: "Quero muito",
    status: "Quero comprar",
    addedAt: todayISO(),
    notes: "Perfeito para o verão",
  },
  {
    id: uid(),
    imageUrl:
      "https://images.unsplash.com/photo-1543163521-1a2727199b1c?auto=format&fit=crop&w=600&q=80",
    name: "Sandália de salto bloco",
    category: "Calçados",
    brand: "Arezzo",
    store: "Arezzo",
    originalPrice: 299.9,
    currentPrice: 299.9,
    buyLink: "https://www.arezzo.com.br",
    color: "Caramelo",
    size: "37",
    priority: "Quero",
    status: "Esperando promoção",
    addedAt: todayISO(),
  },
  {
    id: uid(),
    imageUrl:
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=600&q=80",
    name: "Bolsa tote estruturada",
    category: "Bolsas",
    brand: "Schutz",
    store: "Schutz",
    originalPrice: 699,
    currentPrice: 559,
    buyLink: "https://www.schutz.com.br",
    color: "Off-white",
    size: "Único",
    priority: "Quero muito",
    status: "Quero comprar",
    addedAt: todayISO(),
  },
  {
    id: uid(),
    imageUrl:
      "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=600&q=80",
    name: "Blusa de linho",
    category: "Blusas",
    brand: "Zara",
    store: "Zara",
    originalPrice: 179.9,
    currentPrice: 129.9,
    color: "Bege",
    size: "P",
    priority: "Talvez",
    status: "Comprada",
    addedAt: todayISO(),
    paidPrice: 129.9,
    purchasedAt: todayISO(),
    purchaseNotes: "Achei na liquidação",
  },
  {
    id: uid(),
    imageUrl:
      "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=600&q=80",
    name: "Colar corrente delicada",
    category: "Acessórios",
    brand: "Vivara",
    store: "Vivara",
    originalPrice: 890,
    currentPrice: 890,
    color: "Dourado",
    size: "Único",
    priority: "Quero",
    status: "Desisti da compra",
    addedAt: todayISO(),
    notes: "Vou esperar outra coleção",
  },
];
