import { useEffect, useMemo, useState } from "react";
import { Bot, ExternalLink, Heart, LoaderCircle, Plus, Send, X } from "lucide-react";
import * as api from "../api/closet";
import { formatBRL, type ShopperConversation, type ShopperResult, type ShopperVariation } from "../types";
import { normalizeShopperMerchant } from "../utils/shopperMerchant";
type Message = { role: "user" | "assistant"; content: string };
export function PersonalShopper() {
  const [open,setOpen]=useState(false),[message,setMessage]=useState(""),[conversationId,setConversationId]=useState<string>(),[history,setHistory]=useState<ShopperConversation[]>([]),[messages,setMessages]=useState<Message[]>([]),[all,setAll]=useState<ShopperVariation[]>([]),[shown,setShown]=useState<ShopperVariation[]>([]),[store,setStore]=useState(""),[loading,setLoading]=useState(false),[error,setError]=useState("");
  useEffect(()=>{void api.fetchShopperConversations().then(setHistory).catch(()=>undefined);},[]);
  const merchants=useMemo(()=>[...new Set(all.flatMap(v=>v.offers.map(o=>o.merchant||normalizeShopperMerchant(o.store))))].sort((a,b)=>a.localeCompare(b,"pt-BR")),[all]);
  const offers=shown.flatMap(v=>v.offers);
  const filter=(value:string)=>{setStore(value);setShown(!value?all:all.flatMap(v=>{const offers=v.offers.filter(o=>(o.merchant||normalizeShopperMerchant(o.store))===value);return offers.length?[{...v,offers,imageUrl:offers.find(o=>o.imageUrl)?.imageUrl||v.imageUrl}]:[]}));};
  const load=(variations:ShopperVariation[])=>{setAll(variations);setShown(variations);setStore("");};
  const openConversation=async(id:string)=>{setConversationId(id);setMessages([]);load([]);setError("");setLoading(true);try{const conversation=await api.fetchShopperConversation(id);setMessages(conversation.messages.map(({role,content})=>({role,content})));load(conversation.variations||[]);}catch(e){setError(e instanceof Error?e.message:"Não foi possível abrir a conversa.");}finally{setLoading(false);}};
  const send=async()=>{if(!message.trim()||loading)return;const text=message;setMessage("");setLoading(true);setError("");setMessages(x=>[...x,{role:"user",content:text}]);try{const r=await api.sendShopperMessage(text,conversationId);setConversationId(r.conversationId);load(r.variations||[]);setMessages(x=>[...x,{role:"assistant",content:r.answer}]);void api.fetchShopperConversations().then(setHistory).catch(()=>undefined);}catch(e){setError(e instanceof Error?e.message:"Não foi possível consultar as lojas.");}finally{setLoading(false);}};
  const act=async(result:ShopperResult,action:"save"|"add-to-planner")=>{if(!conversationId)return;try{await api.shopperAction(conversationId,result.id,action);}catch(e){setError(e instanceof Error?e.message:"Esse resultado expirou. Faça a pesquisa novamente.");}};
  return <><button type="button" className="shopper-popup-trigger" onClick={()=>setOpen(true)}><Bot size={21}/><span>Personal Shopper IA</span></button>{open&&<div className="shopper-popup-backdrop" onMouseDown={()=>setOpen(false)}><div className="shopper-popup" onMouseDown={e=>e.stopPropagation()}><button className="shopper-popup-close" onClick={()=>setOpen(false)}><X size={20}/></button><section className="shopper-shell card-soft p-4 sm:p-5"><div className="shopper-heading"><div><p className="planner-kicker"><Bot size={15}/> Personal Shopper IA</p><h2 className="font-display mt-2 text-3xl font-semibold text-brown-deep">Encontre para mim</h2></div></div>{history.length?<div className="shopper-history">{history.slice(0,6).map(x=><button type="button" className={conversationId===x.id?"is-active":""} key={x.id} onClick={()=>void openConversation(x.id)}>{x.title||"Busca sem título"}</button>)}</div>:null}<div className="shopper-chat">{messages.map((x,i)=><p key={i} className={`shopper-message ${x.role}`}>{x.content}</p>)}{loading&&<p className="shopper-message assistant"><LoaderCircle size={16} className="animate-spin"/> Carregando…</p>}</div><form className="shopper-form" onSubmit={e=>{e.preventDefault();void send();}}><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Ex.: Quero uma bolsa elegante até R$ 200"/><button className="btn-primary" disabled={loading||!message.trim()}><Send size={16}/> Buscar</button></form>{error&&<p className="finding-error mt-3">{error}</p>}{all.length?<><div className="shopper-results-head"><h3>Produtos e variações</h3><span>{shown.length} variações · {offers.length} ofertas</span></div><label className="shopper-store-select">Loja<select value={store} onChange={e=>filter(e.target.value)}><option value="">Todas as lojas</option>{merchants.map(x=><option key={x} value={x}>{x}</option>)}</select></label><div className="shopper-grid">{shown.map(v=><article className="shopper-card" key={v.id}><div className="shopper-image">{v.imageUrl?<img src={v.imageUrl} alt={v.title}/>:<span>Imagem indisponível</span>}</div><div className="shopper-card-copy"><h4>{v.title}</h4></div><div className="shopper-offers">{v.offers.map(o=><div className="shopper-offer" key={o.id}><div><b>{o.store}</b><strong>{o.price==null?"Preço não informado":formatBRL(o.price)}</strong></div><div className="shopper-actions"><a className="btn-ghost" href={o.productUrl} target="_blank" rel="noreferrer"><ExternalLink size={14}/> Loja</a><button className="btn-ghost" onClick={()=>void act(o,"save")}><Heart size={14}/> Salvar</button><button className="btn-primary" onClick={()=>void act(o,"add-to-planner")}><Plus size={14}/> Planner</button></div></div>)}</div></article>)}</div></>:null}</section></div></div>}</>;
}
