import { useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2, LoaderCircle, X } from "lucide-react";
import * as api from "../api/closet";
import { formatBRL, type Product } from "../types";

export function PurchaseAnalysisModal({ product, open, onClose }: { product: Product | null; open: boolean; onClose: () => void }) {
  const [data, setData] = useState<api.PurchaseAnalysis | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const rawBudget = localStorage.getItem("purchase-planner-monthly-budget"); const parsedBudget = rawBudget ? Number(rawBudget) : NaN; const budget = Number.isFinite(parsedBudget) && parsedBudget > 0 ? parsedBudget : null;
  useEffect(() => { if (!open || !product) return; const load = async () => { setLoading(true); setError(""); try { setData(await api.fetchPurchaseAnalysis(product.id, budget)); } catch (err) { setError(err instanceof Error ? err.message : "Não foi possível analisar esta compra."); } finally { setLoading(false); } }; void load(); }, [open, product, budget]);
  useEffect(() => { if (!open) return; const closeOnEscape = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; document.addEventListener("keydown", closeOnEscape); return () => document.removeEventListener("keydown", closeOnEscape); }, [open, onClose]);
  if (!open || !product) return null;
  const tone = data && data.score >= 80 ? "good" : data && data.score >= 60 ? "okay" : data && data.score >= 40 ? "review" : "wait";
  return <div className="analysis-backdrop" role="presentation" onMouseDown={onClose}><section className="analysis-modal" role="dialog" aria-modal="true" aria-labelledby="purchase-analysis-title" onMouseDown={(event) => event.stopPropagation()}><header><div><p className="planner-kicker">Análise de compra consciente</p><h2 id="purchase-analysis-title">Vale a pena comprar?</h2><p>{product.name}</p></div><button type="button" className="btn-ghost" onClick={onClose} aria-label="Fechar análise"><X size={17} /></button></header>{loading ? <div className="analysis-loading"><LoaderCircle className="animate-spin" /> Calculando impacto da compra…</div> : error ? <p className="finding-error">{error}</p> : data ? <div className="analysis-body"><div className={`analysis-score ${tone}`}><strong>{data.score}</strong><span>/ 100</span><b>{data.classification}</b></div><p className="analysis-summary">Este item está salvo há {data.daysSaved} dias{data.estimatedCostPerUse != null ? ` e tem custo por uso estimado de ${formatBRL(data.estimatedCostPerUse)}` : "."}{data.budgetPercent != null ? ` Ele consome ${Math.round(data.budgetPercent)}% do orçamento atual.` : ""}</p><div className="analysis-columns"><ReasonList title="Pontos positivos" items={data.positiveReasons} positive /><ReasonList title="Atenção" items={data.warningReasons} /></div><section className="analysis-simulation"><h3>E se eu comprar?</h3><div className="analysis-impact"><span style={{ width: `${Math.min(100, data.budgetImpact.budgetPercent || 0)}%` }} /></div><div className="analysis-metrics"><span>Saldo: <b>{data.budgetImpact.remainingBudget == null ? "Informe orçamento" : formatBRL(data.budgetImpact.remainingBudget)}</b></span><span>Custo por uso: <b>{data.estimatedCostPerUse == null ? "Não informado" : formatBRL(data.estimatedCostPerUse)}</b></span><span>Deixam de caber: <b>{data.budgetImpact.productsNoLongerAffordableCount}</b></span><span>Ainda cabem: <b>{data.productsStillAffordable.length}</b></span></div><AnalysisList label="Próxima recomendada" items={data.nextRecommendedProduct ? [data.nextRecommendedProduct] : []} /><AnalysisList label="Produtos semelhantes" items={data.similarProducts} /><AnalysisList label="Ainda cabem depois" items={data.productsStillAffordable} /><AnalysisList label="Deixam de caber" items={data.productsNoLongerAffordable} /><AnalysisList label="Combo após a compra" items={data.updatedSuggestedCombo.products} total={data.updatedSuggestedCombo.total} /></section></div> : null}</section></div>;
}
function ReasonList({ title, items, positive = false }: { title: string; items: string[]; positive?: boolean }) { return <div className="analysis-reasons"><h3>{positive ? <CheckCircle2 size={16} /> : <AlertTriangle size={16} />}{title}</h3>{items.length ? <ul>{items.map((item) => <li key={item}>{item}</li>)}</ul> : <p>Sem pontos relevantes.</p>}</div>; }
function AnalysisList({ label, items, total }: { label: string; items: Array<{ id: string; name: string; price: number }>; total?: number | null }) { return <div className="analysis-list"><h4>{label}{total != null ? ` · ${formatBRL(total)}` : ""}</h4>{items.length ? items.map((item) => <div key={item.id}><span>{item.name}</span><b>{formatBRL(item.price)}</b></div>) : <p>Nenhum item.</p>}</div>; }
