import { useEffect, useState } from "react";
import { ExternalLink, Pause, Play, Trash2 } from "lucide-react";
import { AppShell } from "../components/AppShell";
import * as api from "../api/closet";
import { formatBRL, type PromotionOffer, type PromotionProvider, type PromotionWatchItem } from "../types";

export function PromotionMonitorPage() {
  const [items, setItems] = useState<PromotionWatchItem[]>([]); const [cep, setCep] = useState(""); const [name, setName] = useState(""); const [maximum, setMaximum] = useState(""); const [offers, setOffers] = useState<PromotionOffer[]>([]); const [providers, setProviders] = useState<PromotionProvider[]>([]); const [message, setMessage] = useState("");
  const load = async () => { try { const [settings, watches, available] = await Promise.all([api.fetchPromotionSettings(), api.fetchPromotionWatchItems(), api.fetchPromotionProviders()]); setCep(settings.shippingPostalCode || ""); setItems(watches); setProviders(available); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível carregar o monitor."); } };
  useEffect(() => { void load(); }, []);
  const add = async (event: React.FormEvent) => { event.preventDefault(); try { await api.savePromotionSettings({ shippingPostalCode: cep || null }); await api.createPromotionWatchItem({ name, searchTerm: name, maximumTotalPrice: Number(maximum.replace(",", ".")), active: true }); setName(""); setMaximum(""); await load(); setMessage("Produto salvo e monitorado."); } catch (error) { setMessage(error instanceof Error ? error.message : "Revise os dados informados."); } };
  const edit = async (item: PromotionWatchItem) => { const nextName = window.prompt("Produto que estou procurando", item.name); const nextMaximum = window.prompt("Preço máximo incluindo frete", String(item.maximumTotalPrice)); if (!nextName || !nextMaximum) return; try { await api.updatePromotionWatchItem(item.id, { name: nextName, searchTerm: nextName, maximumTotalPrice: Number(nextMaximum.replace(",", ".")) }); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível editar."); } };
  const showOffers = async (id: string) => { try { const item = await api.fetchPromotionOffers(id); setOffers((item.offers || []).slice().sort((a, b) => (a.totalPrice ?? Infinity) - (b.totalPrice ?? Infinity))); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível carregar as ofertas."); } };
  return <AppShell><section className="space-y-6"><div><p className="app-eyebrow">Monitor automático</p><h1 className="font-display text-3xl text-stone-800">Promoções que cabem na sua meta</h1><p className="mt-2 text-sm text-stone-500">Alertas só são enviados quando preço + frete estão confirmados.</p></div>
    <form className="rounded-3xl border border-stone-200 bg-white p-5 shadow-sm" onSubmit={add}><div className="grid gap-3 md:grid-cols-3"><label className="field"><span>Produto que estou procurando</span><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Shampoo Wella" required /></label><label className="field"><span>Preço máximo incluindo frete</span><input inputMode="decimal" value={maximum} onChange={(e) => setMaximum(e.target.value)} placeholder="390,00" required /></label><label className="field"><span>CEP para cálculo de frete</span><input value={cep} onChange={(e) => setCep(e.target.value)} onBlur={() => void api.savePromotionSettings({ shippingPostalCode: cep || null }).catch(() => setMessage("CEP inválido."))} placeholder="00000-000" /></label></div><button className="btn-primary mt-4">Salvar e monitorar</button></form>
    {message ? <p className="text-sm text-stone-600" role="status">{message}</p> : null}
    <div className="grid gap-4 md:grid-cols-2">{items.map((item) => <article key={item.id} className="rounded-3xl border border-stone-200 bg-white p-5 shadow-sm"><h2 className="font-display text-xl">{item.name}</h2><p className="mt-1 text-sm text-stone-600">Meta: até {formatBRL(item.maximumTotalPrice)} com frete</p><p className="mt-2 text-sm">{item.active ? "🟢 Monitorando" : "⚪ Pausado"}</p><p className="mt-2 text-xs text-stone-500">Última verificação: {item.lastCheckedAt ? new Date(item.lastCheckedAt).toLocaleString("pt-BR") : "ainda não realizada"}</p>{item.offers?.[0]?.totalPrice != null ? <p className="mt-2 text-sm">Melhor oferta: {formatBRL(item.offers[0].totalPrice)} — {item.offers[0].store}</p> : null}<div className="mt-4 flex flex-wrap gap-2"><button className="btn-secondary" type="button" onClick={() => void showOffers(item.id)}>Ver ofertas</button><button className="btn-secondary" type="button" onClick={() => void edit(item)}>Editar</button><button className="btn-secondary" type="button" onClick={() => void api.updatePromotionWatchItem(item.id, { active: !item.active }).then(load)}>{item.active ? <Pause size={15} /> : <Play size={15} />}{item.active ? " Pausar" : " Retomar"}</button><button className="btn-secondary" type="button" onClick={() => void api.deletePromotionWatchItem(item.id).then(load)}><Trash2 size={15} /> Excluir</button></div></article>)}</div>
    {offers.length ? <section className="rounded-3xl border border-stone-200 bg-white p-5"><h2 className="font-display text-xl">Ofertas encontradas</h2><div className="mt-3 space-y-3">{offers.map((offer) => <div key={offer.id} className="border-b border-stone-100 pb-3 text-sm"><b>{offer.store}</b><p>{offer.title}</p><p>Produto: {formatBRL(offer.productPrice)} · Frete: {offer.shippingPrice == null ? "Frete não confirmado" : formatBRL(offer.shippingPrice)} · <b>Total: {offer.totalPrice == null ? "não confirmado" : formatBRL(offer.totalPrice)}</b></p><a className="inline-flex items-center gap-1 text-stone-700 underline" href={offer.url} target="_blank" rel="noreferrer">Ver oferta <ExternalLink size={13} /></a></div>)}</div></section> : null}
    <p className="text-xs text-stone-500">Lojas: {providers.map((provider) => `${provider.id.replaceAll("_", " ")} (${provider.status === "operational" ? "operacional" : "aguardando integração"})`).join(" · ")}</p>
  </section></AppShell>;
}
