import { useEffect, useState } from "react";
import { ExternalLink, Pause, Play, RefreshCw, Trash2 } from "lucide-react";
import { AppShell } from "../components/AppShell";
import * as api from "../api/closet";
import { formatBRL, type PromotionOffer, type PromotionProvider, type PromotionWatchItem } from "../types";

export function PromotionMonitorPage() {
  const [items, setItems] = useState<PromotionWatchItem[]>([]); const [cep, setCep] = useState(""); const [name, setName] = useState(""); const [maximum, setMaximum] = useState(""); const [offers, setOffers] = useState<PromotionOffer[]>([]); const [providers, setProviders] = useState<PromotionProvider[]>([]); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false); const [checkingId, setCheckingId] = useState("");
  const load = async () => { try { const [settings, watches, available] = await Promise.all([api.fetchPromotionSettings(), api.fetchPromotionWatchItems(), api.fetchPromotionProviders()]); setCep(settings.shippingPostalCode || ""); setItems(watches); setProviders(available); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível carregar o monitor."); } };
  useEffect(() => { void load(); }, []);
  const add = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setMessage("🔎 Procurando ofertas agora..."); try { await api.savePromotionSettings({ shippingPostalCode: cep || null }); const item = await api.createPromotionWatchItem({ name, searchTerm: name, maximumTotalPrice: Number(maximum.replace(",", ".")), active: true }); setName(""); setMaximum(""); setOffers(item.offers || []); await load(); setMessage(item.offers?.length ? "Busca concluída. As ofertas já estão disponíveis." : "Nenhuma oferta encontrada nesta verificação."); } catch (error) { setMessage(error instanceof Error ? error.message : "Revise os dados informados."); } finally { setSaving(false); } };
  const checkNow = async (id: string) => { setCheckingId(id); setMessage("🔎 Procurando ofertas agora..."); try { const item = await api.checkPromotionWatchItemNow(id); setOffers(item.offers || []); await load(); setMessage(item.offers?.length ? "Busca concluída. As ofertas já estão disponíveis." : "Nenhuma oferta encontrada nesta verificação."); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível buscar agora."); } finally { setCheckingId(""); } };
  const edit = async (item: PromotionWatchItem) => { const nextName = window.prompt("Produto que estou procurando", item.name); const nextMaximum = window.prompt("Preço máximo incluindo frete", String(item.maximumTotalPrice)); if (!nextName || !nextMaximum) return; try { await api.updatePromotionWatchItem(item.id, { name: nextName, searchTerm: nextName, maximumTotalPrice: Number(nextMaximum.replace(",", ".")) }); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível editar."); } };
  const showOffers = async (id: string) => { try { const item = await api.fetchPromotionOffers(id); setOffers((item.offers || []).slice().sort((a, b) => (a.totalPrice ?? Infinity) - (b.totalPrice ?? Infinity))); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível carregar as ofertas."); } };
  return <AppShell><section className="space-y-6"><div><p className="app-eyebrow">Monitor automático</p><h1 className="font-display text-3xl text-stone-800">Promoções que cabem na sua meta</h1><p className="mt-2 text-sm text-stone-500">Alertas só são enviados quando preço + frete estão confirmados.</p></div>
    <form className="rounded-3xl border border-stone-200 bg-white p-5 shadow-sm" onSubmit={add}><div className="grid gap-3 md:grid-cols-3"><label className="field"><span>Produto que estou procurando</span><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Shampoo Wella" required disabled={saving} /></label><label className="field"><span>Preço máximo incluindo frete</span><input inputMode="decimal" value={maximum} onChange={(e) => setMaximum(e.target.value)} placeholder="390,00" required disabled={saving} /></label><label className="field"><span>CEP para cálculo de frete</span><input value={cep} onChange={(e) => setCep(e.target.value)} placeholder="00000-000" required disabled={saving} /></label></div><button className="btn-primary mt-4" disabled={saving}>{saving ? "🔎 Procurando ofertas agora..." : "Salvar e monitorar"}</button></form>
    {message ? <p className="text-sm text-stone-600" role="status">{message}</p> : null}
    <div className="grid gap-4 md:grid-cols-2">{items.map((item) => <article key={item.id} className="rounded-3xl border border-stone-200 bg-white p-5 shadow-sm"><h2 className="font-display text-xl">{item.name}</h2><p className="mt-1 text-sm text-stone-600">Meta: até {formatBRL(item.maximumTotalPrice)} com frete</p><p className="mt-2 text-sm">{item.active ? "🟢 Monitorando" : "⚪ Pausado"}</p><p className="mt-2 text-xs text-stone-500">Última verificação: {item.lastCheckedAt ? new Date(item.lastCheckedAt).toLocaleString("pt-BR") : "ainda não realizada"}</p>{item.offers?.[0]?.totalPrice != null ? <p className="mt-2 text-sm">Melhor oferta: {formatBRL(item.offers[0].totalPrice)} — {item.offers[0].store}</p> : item.lastCheckedAt ? <p className="mt-2 text-sm text-stone-500">Nenhuma oferta encontrada nesta verificação.</p> : null}<div className="mt-4 flex flex-wrap gap-2"><button className="btn-secondary" type="button" onClick={() => void checkNow(item.id)} disabled={checkingId === item.id || !item.active}><RefreshCw size={15} className={checkingId === item.id ? "animate-spin" : ""} /> {checkingId === item.id ? "Buscando..." : "Buscar agora"}</button><button className="btn-secondary" type="button" onClick={() => void showOffers(item.id)}>Ver ofertas</button><button className="btn-secondary" type="button" onClick={() => void edit(item)}>Editar</button><button className="btn-secondary" type="button" onClick={() => void api.updatePromotionWatchItem(item.id, { active: !item.active }).then(load)}>{item.active ? <Pause size={15} /> : <Play size={15} />}{item.active ? " Pausar" : " Retomar"}</button><button className="btn-secondary" type="button" onClick={() => void api.deletePromotionWatchItem(item.id).then(load)}><Trash2 size={15} /> Excluir</button></div></article>)}</div>
    {offers.length ? <section className="rounded-3xl border border-stone-200 bg-white p-5"><div className="flex items-end justify-between gap-3"><div><p className="app-eyebrow">Resultados da busca</p><h2 className="font-display text-2xl">Ofertas encontradas</h2></div><span className="text-sm text-stone-500">{offers.length} ofertas</span></div><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{offers.map((offer) => <article key={offer.id} className="overflow-hidden rounded-2xl border border-stone-200 bg-stone-50"><div className="aspect-square bg-stone-100">{offer.imageUrl ? <img src={offer.imageUrl} alt={offer.title} className="h-full w-full object-contain p-3" /> : <div className="flex h-full items-center justify-center text-sm text-stone-400">Sem foto disponível</div>}</div><div className="p-4"><p className="text-xs font-semibold uppercase tracking-wide text-stone-500">{offer.store}</p><h3 className="mt-1 line-clamp-2 min-h-12 font-semibold text-stone-800">{offer.title}</h3><p className="mt-3 text-sm text-stone-600">Produto: {formatBRL(offer.productPrice)}</p><p className="text-sm text-stone-600">Frete: {offer.shippingPrice == null ? "Não confirmado" : formatBRL(offer.shippingPrice)}</p><p className="mt-2 text-lg font-bold text-stone-800">Total: {offer.totalPrice == null ? "A confirmar" : formatBRL(offer.totalPrice)}</p>{offer.discountPercentage ? <p className="text-sm text-emerald-700">{offer.discountPercentage}% de desconto</p> : null}<a className="mt-3 inline-flex items-center gap-1 text-sm font-semibold text-stone-700 underline" href={offer.url} target="_blank" rel="noreferrer">Ver oferta <ExternalLink size={13} /></a></div></article>)}</div></section> : null}
    <p className="text-xs text-stone-500">Lojas: {providers.map((provider) => `${provider.id.replaceAll("_", " ")} (${provider.status === "operational" ? "operacional" : "aguardando integração"})`).join(" · ")}</p>
  </section></AppShell>;
}
